name: Tst Action
on: push
jobs:
  Commit_Message_Check_lxl:
    name: commit message check
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '1000'

      - name: Get recent commits
        id: git_log
        run: echo "::set-output name=commits::$(git log --pretty=format:'%h - %an, %ar : %s' -n 5)"

      - name: Print recent commits
        run: echo "${{ steps.git_log.outputs.commits }}"

      - name: Process commits
        run: |
          COMMIT_MSG="${{ steps.git_log.outputs.commits }}"
          IFS=$'\n'
          for line in $COMMIT_MSG; do
            echo "Commit: $line"
          done