name: Tst Action
on: push
jobs:
  Commit_Message_Check_lxl:
    name: commit message check
    runs-on: windows-latest
    steps:
      - id: condition_check
        name: checkout commit message
        run: |
          # PowerShell 脚本循环输出 HelloWorld 5 次
          for ($i = 1; $i -le 5; $i++) {
            Write-Host "HelloWorld"
            Write-Host "$i"
          }


