name: Tst Action
on: push
jobs:
  Commit_Message_Check_lxl:
    name: commit message check
    runs-on: windows-latest
    steps:
      - id: step1
        run: |
          # echo "The commit message is:${{ github.event.head_commit.message }}"
          echo "hello world"
          $pattern ='(EDW)-[0-9]+ '
          if ("${{ github.event.head_commit.message }}" -match $pattern){
            echo "Valid commit message!"
          }
           # echo "enironment: ${{ github.event_name }}"
        continue-on-error: false