name: merger Action TEST
on:
  pull_request:
      branches:
        - master
jobs:
  Merger_from_master_to_prep_lxl:
    name: Merger from master to prep
    runs-on: windows-latest
    steps:
      - id: step1
        name: print source and target branch
        run: |
          echo " target branch ${{ github.event.pull_request.base.ref }} source branche ${{ github.event.pull_request.head.ref }} "
      - id: step2
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master
      - id: step3
        name: Create Pull Request to prep
        uses: peter-evans/create-pull-request@v3
        with:
          title: Sync master to prep
          body: This PR syncs the master branch to the prep branch.
          branch: prep
          base: prep
          labels: auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}