name: merger Action TEST
on:
  pull_request:
      branches:
        - master
jobs:
  Merger_from_master_to_prep_lxl:
    name: Merger from master to prep
    runs-on: windows-latest
    steps:
      - id: step1
        name: print source and target branch
        run: |
          echo " target branch ${{ github.event.pull_request.base.ref }} source branche ${{ github.event.pull_request.head.ref }} "
          echo "token1 is ${{ secrets.RELEASE_TOKEN }}"
          echo "token2 is ${{ secrets.GITHUB_TOKEN }}"
          echo "token3 is ${{ secrets.DEPENDABOT_TOKEN }}"
          echo "author: ${{ github.actor }}"
      - id: step2
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master
      - id: step3
        name: Setup Git User
        run: |
          git config --global user.name "ccc13781430740"
          git config --global user.email "13781430740@163.com"
      - id: step4
        name: Create Pull Request to prep
        uses: peter-evans/create-pull-request@v5
        with:
          title: Sync master to prep
          body: This PR syncs the master branch to the prep branch.
          branch: prep
          base: master
          labels: auto-merge
          token: ${{ secrets.GITHUB_TOKEN }}